version: '3.9'
services:
  postgis:
    image: postgis/postgis:13-3.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: demo123
      POSTGRES_DB: subjectivity
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d subjectivity" ]
      interval: 10s
      timeout: 5s
      retries: 5
  spring-boot-app:
    build: .
    depends_on:
      postgis:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgis:5432/subjectivity
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=demo123
      - SERVER_SERVLET_CONTEXT_PATH=/